basic: {}
nerfchunk:
  lr: 0.0005
  lr_scheduler: CosineOneCycle
  net: nerf
  optimizer: Adam
  warmup: 100
nerfchunk_c:
  lr: 0.0005
  lr_scheduler: CosineOneCycle
  net: nerf_c
  optimizer: Adam
nerfchunk_f:
  lr: 0.0005
  lr_scheduler: CosineOneCycle
  net: nerf_f
  optimizer: Adam
transformer_train:
  grad_clip: 1.0
  lr: 0.001
  lr_scheduler: CosineOneCycle
  net: net
  optimizer: AdamW
  warmup: 5
  weight_decay: 0.1
